using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Reflection;
using BannerlordTwitch.Util;
using TaleWorlds.Engine;
using TaleWorlds.Library;
using YamlDotNet.Serialization;
using Path = System.IO.Path;

namespace BannerlordTwitch.Rewards
{
    public static partial class ActionManager
    {
        internal static void GenerateDocumentation()
        {
            var docs = new List<string>
            {
                "<!DOCTYPE html><html>",
                "<head>",
                "<link rel=\"stylesheet\" href=\"Bannerlord-Twitch-Documentation.css\">",
                "</head>",
                "<body>",
                "<div class=\"content\">",
                "<h1>Bannerlord-Twitch Module Documentation</h1>",
                "<p>This is autogenerated from the active BLT modules.</p>"
            };

            var documentedTypes = new List<Type>();
            docs.Add($"<h2>Reward</h2>");
            DocumentType(docs, typeof(Reward), documentedTypes);
            docs.Add($"<h3>Reward Actions (each is documented fully further down)</h3>");
            HtmlTable(docs,
                new[] {"Name", "Description"},
                rewardHandlers.Values.Select(v => new[]
                {
                    LinkToAnchor(v.GetType().Name, "Action"),
                    DocStr(v.GetType()) ?? "(none)"
                }), "aclist");

            docs.Add($"<h2>Command</h2>");
            DocumentType(docs, typeof(Command), documentedTypes);
            docs.Add($"<h3>Command Handlers (each is documented fully further down)</h3>");
            HtmlTable(docs,
                new[] {"Name", "Description"},
                commandHandlers.Values
                    .Select(v => new[]
                    {
                        LinkToAnchor(v.GetType().Name, "Command"),
                        DocStr(v.GetType()) ?? "(none)"
                    }), "aclist");

            foreach (var action in rewardHandlers.Values)
            {
                docs.Add($"<h2>{MakeAnchor(action.GetType().Name, "Action")} Action Settings</h2>");
                DocumentActionOrCommand(docs, action.GetType(), action.RewardConfigType, documentedTypes);
            }

            foreach (var command in commandHandlers.Values)
            {
                docs.Add($"<h2>{MakeAnchor(command.GetType().Name, "Command")} Command Handler Settings</h2>");
                DocumentActionOrCommand(docs, command.GetType(), command.HandlerConfigType, documentedTypes);
            }

            docs.Add("</div></html></body>");
            try
            {
                string cssFileName = Path.Combine(Path.GetDirectoryName(typeof(Settings).Assembly.Location), "..", "..",
                    "Bannerlord-Twitch-Documentation.css");
                string css = File.ReadAllText(cssFileName);
                Common.PlatformFileHelper.SaveFileString(new (EngineFilePaths.ConfigsPath, "Bannerlord-Twitch-Documentation.css"), css);
                Common.PlatformFileHelper.SaveFileString(new (EngineFilePaths.ConfigsPath, "Bannerlord-Twitch-Documentation.html"),
                    string.Join("\n", docs.Select(s => s + "  ")));
            }
            catch (Exception e)
            {
                Log.Error($"Couldn't write documentation: {e.Message}");
            }
        }

        private static void DocumentActionOrCommand(ICollection<string> docs, Type objectType, Type settingsType,
            List<Type> documentedTypes)
        {
            string docStr = DocStr(objectType);
            docs.Add(docStr != null
                ? $"<p>{docStr}</p>"
                : $"<p>No documentation provided.</p>");

            if (settingsType != null)
            {
                DocumentType(docs, settingsType, documentedTypes);
            }
        }

        private static string LinkToAnchor(string text, string anchorTag = null)
            => $"<a href=\"#{text}{anchorTag ?? ""}\">{text}</a>";

        private static string MakeAnchor(string text, string anchorTag = null)
            => $"<a name=\"{text}{anchorTag ?? ""}\">{text}</a>";

        private static string DocStr(MemberInfo objectType) =>
            (objectType.GetCustomAttributes(typeof(DescriptionAttribute)).FirstOrDefault() as DescriptionAttribute)?.Description;

        private static void DocumentType(ICollection<string> docs, Type typeToDocument, List<Type> documentedTypes)
        {
            documentedTypes.Add(typeToDocument);

            string docStr = DocStr(typeToDocument);
            if (docStr != null)
            {
                docs.Add($"<p>{docStr}</p>");
            }

            static string GetSimpleTypeName(Type t)
            {
                switch (Type.GetTypeCode(t))
                {
                    case TypeCode.String: return "string";
                    case TypeCode.Boolean: return "bool";
                    case TypeCode.Byte:
                    case TypeCode.Char:
                    case TypeCode.SByte:
                    case TypeCode.Int16:
                    case TypeCode.UInt16:
                    case TypeCode.Int32:
                    case TypeCode.UInt32:
                    case TypeCode.Int64:
                    case TypeCode.UInt64: return "int";
                    case TypeCode.Single:
                    case TypeCode.Double:
                    case TypeCode.Decimal: return "float";
                    default: return t.Name;
                }
            }

            static string GetFieldTypeName(FieldInfo f)
            {
                return Nullable.GetUnderlyingType(f.FieldType) != null
                    ? GetSimpleTypeName(Nullable.GetUnderlyingType(f.FieldType)) + " (optional)"
                    : GetSimpleTypeName(f.FieldType);
            }

            object settingsDefaults = Activator.CreateInstance(typeToDocument);

            var documentedFieldTypes = settingsDefaults.GetType()
                .GetFields()
                .Select(fi => fi.FieldType.IsArray ? fi.FieldType.GetElementType() : fi.FieldType)
                .Where(fi => fi?.GetCustomAttributes(typeof(DescriptionAttribute)).Any() == true);

            HtmlTable(docs, new[]
                {
                    "Name", "Type", "Default Value", "Description"
                },
                settingsDefaults.GetType().GetFields()
                    .Select(f => new[]
                    {
                        f.Name,
                        $"<code>{(documentedFieldTypes.Contains(f.FieldType) ? LinkToAnchor(f.Name) : GetFieldTypeName(f))}</code>",
                        f.FieldType.IsPrimitive ? $"<code>{f.GetValue(settingsDefaults)}</code>" : "(none)",
                        DocStr(f) ?? "(none)"
                    }));

            docs.Add("<h3>Example:</h3>");
            docs.Add("<code class=\"example\">");
            docs.Add(new SerializerBuilder().Build().Serialize(settingsDefaults).Replace("\n", "<br>"));
            docs.Add("</code>");

            foreach (var sft in documentedFieldTypes.Where(t => !documentedTypes.Contains(t)))
            {
                if (!documentedTypes.Contains(sft))
                {
                    docs.Add($"<h2>{MakeAnchor(sft.Name)} Subtype</h2>");
                    DocumentType(docs, sft, documentedTypes);
                }
            }
        }

        private static void HtmlTable(ICollection<string> docs, IEnumerable<string> headers,
            IEnumerable<IEnumerable<string>> rows, string cssClass = null)
        {
            docs.Add(cssClass != null ? $"<table class=\"{cssClass}\">" : "<table>");

            docs.Add("<tr>");
            foreach (string header in headers)
            {
                docs.Add($"<th>{header}</th>");
            }

            docs.Add("</tr>");
            foreach (var row in rows)
            {
                docs.Add("<tr>");
                foreach (string cell in row)
                {
                    docs.Add($"<td>{cell}</td>");
                }

                docs.Add("</tr>");
            }

            docs.Add("</table>");
        }
    }
}