using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using BannerlordTwitch.Util;
using JetBrains.Annotations;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TaleWorlds.Core;
using TaleWorlds.Library;
using YamlDotNet.Serialization;

namespace BannerlordTwitch.Rewards
{
    public class DescAttribute : Attribute
    {
        public string Desc;

        public DescAttribute(string desc)
        {
            this.Desc = desc;
        }
    }
    
    public static class RewardManager
    {
        private static readonly Dictionary<string, IAction> actions = new();
        private static readonly Dictionary<string, IHandler> commands = new();
        
        public static void Init()
        {
            RegisterAll(typeof(RewardManager).Assembly);
        }

        public static void RegisterAll(Assembly assembly)
        {
            var redemptionActionTypes = assembly
                .GetTypes()
                .Where(t => typeof(IAction).IsAssignableFrom(t) && !t.IsAbstract);
            foreach (var redemptionActionType in redemptionActionTypes)
            {
                RegisterAction((IAction) Activator.CreateInstance(redemptionActionType));
            }

            var botCommands = assembly
                .GetTypes()
                .Where(t => typeof(IHandler).IsAssignableFrom(t) && !t.IsAbstract);
            foreach (var botCommandType in botCommands)
            {
                RegisterCommand((IHandler) Activator.CreateInstance(botCommandType));
            }
        }

        public static bool RegisterAction(IAction action)
        {
            var id = action.GetType().Name;
            if (actions.ContainsKey(id))
            {
                Log.Error($"Reward Action {id} already registered, please choose another name");
                return false;
            }
            Log.Trace($"Registered Reward Action {id}");
            actions.Add(id, action);
            return true;
        }
        
        public static bool RegisterCommand(IHandler command)
        {
            var id = command.GetType().Name;
            if (commands.ContainsKey(id))
            {
                Log.Error($"Bot Command {id} already registered, please choose another name");
                return false;
            }
            Log.Trace($"Registered Bot Command {id}");
            commands.Add(id, command);
            return true;
        }

        public static object FindGlobalConfig(string id) => BLTModule.TwitchService.FindGlobalConfig(id);

        internal static void GenerateDocumentation()
        {
            var docs = new List<string>
            {
                "<!DOCTYPE html><html>",
                @"<head>
                <style>
table{
width:80%;
margin-left: 5%;
margin-right: 15%;
}
table, th, td {
border: 1px solid black;
border-collapse: collapse;
font-family: verdana;
}
th, td {
padding: 4px 10px;
text-align: left;
}
table td:nth-child(1) {
width: 30%;
}
table td:nth-child(2) {
width: 20%;
}
table td:nth-child(3) {
width: 50%;
}
table tr:nth-child(even) {
background-color: #ddd;
}
table tr:nth-child(odd) {
background-color: #fff;
}
table th {
background-color: black;
color: white;
}
h1, h2, h3, p {
font-family: verdana;
}
                </style>
                </head>",
                "<body>",
                "<h1>Bannerlord-Twitch Module Documentation</h1>",
                "<p>This is autogenerated from the active BLT modules.</p>"
            };
            foreach (var action in actions)
            {
                docs.Add($"<h2>{action.Key} Action Settings</h2>");
                DocumentObject(docs, action.Value.GetType(), action.Value.ActionConfigType);
            }
            
            foreach (var command in commands)
            {
                docs.Add($"<h2>{command.Key} Command Settings</h2>");
                DocumentObject(docs, command.Value.GetType(), command.Value.HandlerConfigType);
            }

            docs.Add("</html></body>");
            File.WriteAllLines(Path.Combine(Common.PlatformFileHelper.DocumentsPath,
                "Mount and Blade II Bannerlord", "Configs", "Bannerlord-Twitch-Documentation.html"), docs.Select(s => s + "  "));
        }

        private static void DocumentObject(ICollection<string> docs, Type type, Type settingsType)
        {
            var docStr = (type.GetCustomAttributes(typeof(DescAttribute)).FirstOrDefault() as DescAttribute)
                ?.Desc;
            if (docStr != null)
            {
                docs.Add($"<p>{docStr}</p>");
            }

            var settingsDefaults = Activator.CreateInstance(settingsType);
            docs.Add("<table>");
            docs.Add("<tr><th>Name</th><th>Default</th><th>Description</th></tr>");
            foreach (var f in settingsDefaults.GetType().GetFields())
            {
                docs.Add("<tr>");
                var fieldDocStr = (f.GetCustomAttributes(typeof(DescAttribute)).FirstOrDefault() as DescAttribute)?.Desc;
                docs.Add($"<td><code>{f.Name}</code></td>");
                docs.Add($"<td>{f.GetValue(settingsDefaults)}</td>");
                docs.Add(fieldDocStr != null
                    ? $"<td>{fieldDocStr}</td>"
                    : $"<td>-</td>");
                docs.Add("</tr>");
            }

            docs.Add("</table>");
        }

        internal static object ConvertObject(object obj, Type type) =>
            new DeserializerBuilder().Build().Deserialize(
                new SerializerBuilder().Build().Serialize(obj),
                type);

        internal static void Command(string id, string args, CommandMessage commandMessage, object config)
        {
            if (commands.TryGetValue(id, out var cmdHandler))
            {
                try
                {
                    if (cmdHandler.HandlerConfigType != null)
                    {
                        config = ConvertObject(config, cmdHandler.HandlerConfigType);
                    }

                    cmdHandler.Execute(args, commandMessage, config);
                }
                catch (Exception e)
                {
                    Log.ScreenCritical($"Command {id} failed with exception {e.Message}, game might be unstable now!");
                    Log.Error(e.ToString());
                }
            }
            else
            {
                Log.ScreenFail($"Command with id {id} couldn't be found, check Commands config");
            }
        }

        internal static bool Enqueue(string actionId, Guid redemptionId, string message, string userName, object config)
        {
            if (!actions.TryGetValue(actionId, out var action))
            {
                Log.Error($"Action with the id {actionId} doesn't exist");
                return false;
            }

            var st = new Stopwatch();
            st.Start();
            try
            {
                if (action.ActionConfigType != null)
                {
                    config = ConvertObject(config, action.ActionConfigType);
                }
                
                action.Enqueue(redemptionId, message, userName, config);
            }
            catch (Exception e)
            {
                Log.ScreenCritical($"Action {actionId} failed with exception {e.Message}, game might be unstable now!");
                Log.Error(e.ToString());
                NotifyCancelled(redemptionId, $"Error occurred while trying to process the redemption");
            }

            if (st.ElapsedMilliseconds > 5)
            {
                Log.Info($"Action {actionId} took {st.ElapsedMilliseconds}ms to Enqueue, this is too slow!");
            }

            return true;
        }

        public static void NotifyComplete(Guid id, string status = null)
        {
            BLTModule.TwitchService.RedemptionComplete(id, status);
        }
        
        public static void NotifyCancelled(Guid id, string reason = null)
        {
            BLTModule.TwitchService.RedemptionCancelled(id, reason);
        }

        public static void SendChat(params string[] messages)
        {
            BLTModule.TwitchService.SendChat(messages);
        }
        
        public static void SendReply(string replyId, params string[] messages)
        {
            BLTModule.TwitchService.SendReply(replyId, messages);
        }
    }
}